In [6]:
import pandas as pd
import numpy as np
from pathlib import Path
# Get the directory where the current notebook is located
current_dir = Path.cwd()

# Define the path relative to the notebook
# This works regardless of the operating system
data_path = current_dir.parent / "data" / "epidemiology.csv"

In [7]:
data = pd.read_csv(data_path)

In [23]:
data[data['date'] == pd.Timestamp(2021, 12, 1)]

,date,location_key,new_confirmed,new_deceased,new_recovered,new_tested,cumulative_confirmed,cumulative_deceased,cumulative_recovered,cumulative_tested
700,2021-12-01,AD,232.0,1.0,NaN,NaN,17658.0,132.0,NaN,NaN
1687,2021-12-01,AE,64.0,0.0,NaN,248038.0,742173.0,2148.0,NaN,102201007.0
2674,2021-12-01,AF,28.0,1.0,NaN,NaN,157387.0,7310.0,NaN,NaN
3336,2021-12-01,AF_BAL,0.0,0.0,7.0,NaN,7634.0,566.0,7191.0,NaN
3833,2021-12-01,AF_BAM,0.0,0.0,0.0,NaN,3091.0,52.0,3034.0,NaN
...,...,...,...,...,...,...,...,...,...,...
12522045,2021-12-01,ZA_WC_DC3,18.0,NaN,NaN,NaN,23767.0,NaN,NaN,NaN
12522917,2021-12-01,ZA_WC_DC4,22.0,NaN,NaN,NaN,57703.0,NaN,NaN,NaN
12523693,2021-12-01,ZA_WC_DC5,3.0,NaN,NaN,NaN,5587.0,NaN,NaN,NaN
12524551,2021-12-01,ZM,25.0,0.0,NaN,5241.0,210220.0,3667.0,NaN,2731797.0
12525538,2021-12-01,ZW,1042.0,0.0,NaN,8292.0,136379.0,4707.0,NaN,1472303.0

In [32]:
data[data['location_key'] == 'AE']

,date,location_key,new_confirmed,new_deceased,new_recovered,new_tested,cumulative_confirmed,cumulative_deceased,cumulative_recovered,cumulative_tested
987,2020-01-01,AE,0.0,0.0,NaN,NaN,0.0,0.0,NaN,NaN
988,2020-01-02,AE,0.0,0.0,NaN,NaN,0.0,0.0,NaN,NaN
989,2020-01-03,AE,0.0,0.0,NaN,NaN,0.0,0.0,NaN,NaN
990,2020-01-04,AE,0.0,0.0,NaN,NaN,0.0,0.0,NaN,NaN
991,2020-01-05,AE,0.0,0.0,NaN,NaN,0.0,0.0,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...
1969,2022-09-09,AE,412.0,0.0,NaN,NaN,1019625.0,2342.0,NaN,NaN
1970,2022-09-10,AE,400.0,0.0,NaN,NaN,1020025.0,2342.0,NaN,NaN
1971,2022-09-11,AE,387.0,0.0,NaN,NaN,1020412.0,2342.0,NaN,NaN
1972,2022-09-12,AE,377.0,0.0,NaN,NaN,1020789.0,2342.0,NaN,NaN
1973,2022-09-13,AE,402.0,0.0,NaN,NaN,1021191.0,2342.0,NaN,NaN

In [15]:
data.info()

<class 'pandas.DataFrame'>
RangeIndex: 12525825 entries, 0 to 12525824
Data columns (total 10 columns):
 #   Column                Dtype
---  ------                -----
 0   date                  datetime64[us]
 1   location_key          str
 2   new_confirmed         float64
 3   new_deceased          float64
 4   new_recovered         float64
 5   new_tested            float64
 6   cumulative_confirmed  float64
 7   cumulative_deceased   float64
 8   cumulative_recovered  float64
 9   cumulative_tested     float64
dtypes: datetime64[us](1), float64(8), str(1)
memory usage: 955.6 MB

In [38]:
keys = data['location_key'].unique()
keys_df = pd.DataFrame(keys, columns=['location_key'])

In [39]:
keys_df.to_csv("keys.csv", index=False)