In [6]:
import pandas as pd
import numpy as np
from pathlib import Path
# Get the directory where the current notebook is located
current_dir = Path.cwd()

# Define the path relative to the notebook
# This works regardless of the operating system
data_path = current_dir.parent / "data" / "epidemiology.csv"

In [7]:
data = pd.read_csv(data_path)

In [8]:
data.info()

<class 'pandas.DataFrame'>
RangeIndex: 12525825 entries, 0 to 12525824
Data columns (total 10 columns):
 #   Column                Dtype
---  ------                -----
 0   date                  str
 1   location_key          str
 2   new_confirmed         float64
 3   new_deceased          float64
 4   new_recovered         float64
 5   new_tested            float64
 6   cumulative_confirmed  float64
 7   cumulative_deceased   float64
 8   cumulative_recovered  float64
 9   cumulative_tested     float64
dtypes: float64(8), str(2)
memory usage: 955.6 MB

In [9]:
data.head(5)

,date,location_key,new_confirmed,new_deceased,new_recovered,new_tested,cumulative_confirmed,cumulative_deceased,cumulative_recovered,cumulative_tested
0,2020-01-01,AD,0.0,0.0,NaN,NaN,0.0,0.0,NaN,NaN
1,2020-01-02,AD,0.0,0.0,NaN,NaN,0.0,0.0,NaN,NaN
2,2020-01-03,AD,0.0,0.0,NaN,NaN,0.0,0.0,NaN,NaN
3,2020-01-04,AD,0.0,0.0,NaN,NaN,0.0,0.0,NaN,NaN
4,2020-01-05,AD,0.0,0.0,NaN,NaN,0.0,0.0,NaN,NaN

In [11]:
data.describe()

,new_confirmed,new_deceased,new_recovered,new_tested,cumulative_confirmed,cumulative_deceased,cumulative_recovered,cumulative_tested
count,1.247580e+07,1.166714e+07,3.980462e+06,3.194489e+06,1.232704e+07,1.147482e+07,3.991157e+06,3.012920e+06
mean,1.111905e+02,1.274817e+00,2.104549e+02,2.509508e+03,3.539969e+04,5.874310e+02,6.655680e+04,9.057159e+05
std,1.165983e+04,8.808127e+01,1.898989e+04,2.955847e+05,6.135014e+05,9.228857e+03,1.572899e+06,1.518347e+07
min,-5.045418e+06,-6.381100e+04,-1.001683e+07,-3.541552e+08,0.000000e+00,0.000000e+00,-3.000000e+00,0.000000e+00
25%,0.000000e+00,0.000000e+00,0.000000e+00,1.000000e+00,2.020000e+02,3.000000e+00,0.000000e+00,3.460000e+02
50%,1.000000e+00,0.000000e+00,0.000000e+00,7.000000e+00,1.034000e+03,1.800000e+01,7.000000e+00,1.890000e+03
75%,1.100000e+01,0.000000e+00,5.000000e+00,5.200000e+01,5.002000e+03,8.100000e+01,3.099000e+03,1.508900e+04
max,5.047094e+06,6.383000e+04,9.967355e+06,3.541856e+08,9.244050e+07,1.005195e+06,2.345841e+08,9.214000e+09